package sscce.smartReferenceNoCheckingError.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Container = 0;
  public static final int Def = 1;
  public static final int Ref = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x1dc361589d7b4b9dL, 0x8929b0fa0d7a49b0L);
    builder.put(0x18167a095cf2be41L, Container);
    builder.put(0x18167a095cf2be42L, Def);
    builder.put(0x18167a095cf2be7aL, Ref);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
