package TableNavDemo.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (index_xbvbvu_a0a.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Cell_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Root_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Row_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new RowHeader_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex index_xbvbvu_a0a = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x8bbc6835af784affL, 0xadb1795fe9a60846L, 0x7970127f6e0f9c51L), MetaIdFactory.conceptId(0x8bbc6835af784affL, 0xadb1795fe9a60846L, 0x7970127f6e0f88d0L), MetaIdFactory.conceptId(0x8bbc6835af784affL, 0xadb1795fe9a60846L, 0x7970127f6e0f9ae0L), MetaIdFactory.conceptId(0x8bbc6835af784affL, 0xadb1795fe9a60846L, 0x7970127f6e13ed72L)).seal();
}
