package TableNavDemo.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Cell = 0;
  public static final int Root = 1;
  public static final int Row = 2;
  public static final int RowHeader = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x8bbc6835af784affL, 0xadb1795fe9a60846L);
    builder.put(0x7970127f6e0f9c51L, Cell);
    builder.put(0x7970127f6e0f88d0L, Root);
    builder.put(0x7970127f6e0f9ae0L, Row);
    builder.put(0x7970127f6e13ed72L, RowHeader);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
